name: setup

description: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: npm

    - name: Install packages
      run: npm install
      shell: bash

    - name: Setup foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Compile Foundry Contracts
      run: forge build
      shell: bash
      working-directory: ./evm
